### ISSUE TITLE
System clock drift causes git checkout problem

### ISSUE THREAD

**Issue by davidknaack** [MediaMath/grim#105]
If the system clock drifts too far github checkouts will fail.

The provision script could include install of ntp to prevent this.

**Comment by logie17** [comment]
:+1:

**Comment by kklipsch** [comment]
So we can try to make it so grim is resistant to clock drift, but can you describe more precisely what is happening?

**Comment by davidknaack** [comment]
Computer clocks drift, and VM clocks tend to drift even more if the host is not synchronizing the guest clock.

If the clock drifts too far ssl certificate validation will fail due to clock skew limits (useful for replay attack protection). If ssl fails, grim can't get updates from github repos, and you get output.log files like:

sudo: unable to resolve host ####
make: Warning: File `db_start.mk' has modification time 59 s in the future
go get gopkg.in/tylerb/graceful.v1
Cloning into '###'...
fatal: remote error: Git repository not found

Keeping the clock in sync fixes the ssl validation issues and keeps grim happy.

**Comment by kklipsch** [comment]
You will also get problems with make.  Unfortunately i dont think there is anything to be done about this with grim itself, these are OS level and external application protections.
