### ISSUE TITLE
grimd logging

### ISSUE THREAD

**Issue by kklipsch** [MediaMath/grim#30]
A) make results directory at beginning of build.
B) log the hook to results
C) log to the results directory at a minimum:
- build start
- workspace created
- build script started
- build script finished error/no error

D) grimd logging should include the creation of the results directory at a minimum.

**Comment by varun06** [comment]
@bhand-mm Is (A) in issue description is done with your last fix, I see `go writeOutput(resultPath, outputChan)` just after getting env variables in build function?

**Comment by bhand-mm** [comment]
@varun06 I changed it to make the directory earlier but I think for this task it needs to change to make it even earlier

**Comment by kklipsch** [comment]
Closed by #48
