### ISSUE TITLE
grimd log should have build information in it

### ISSUE THREAD

**Issue by kklipsch** [MediaMath/grim#81]

**Comment by logie17** [comment]
Can you elaborate more on what you mean here?

**Comment by bhand-mm** [comment]
A lot of our projects have a linker-injected build version to indicate which binary they are running.

**Comment by logie17** [comment]
Is this build information specific to grim or to the project it is building? Right now in the grimd logs I'm seeing lines that contain this:
```
grimd-1438016570-20150727.170250 ...
```

That looks like a grim build number?

**Comment by bhand-mm** [comment]
Yep!  This is probably an old issue.
