### ISSUE TITLE
Global and local config timeouts do not seem to be honored

### ISSUE THREAD

**Issue by logie17** [MediaMath/grim#96]

**Comment by kklipsch** [comment]
Global timeout isnt even a thing.  We can add it as a feature if we want.  As for local timeouts there is definitely a problem that the timeout does not kill the whole process tree.

**Comment by logie17** [comment]
The problem I'm seeing if I set a local timeout at a very high value it still will kill the build before it reaches the threshold.

**Comment by kklipsch** [comment]
Oh really?  Ok that is a different issue.

**Comment by bhand-mm** [comment]
That was due to a json parsing bug I had introduced and since fixed.  This should be closable now.

**Comment by logie17** [comment]
:+1: I have verified that timeouts are honored now
